### ISSUE TITLE
ModuleNotFoundError: No module named 'altair.vegalite.v4'

### ISSUE THREAD

**Issue by jmayank23** [alejandro-ao/langchain-ask-pdf#8]
<img width="987" alt="Screen Shot 2023-05-11 at 6 27 20 PM" src="https://github.com/alejandro-ao/langchain-ask-pdf/assets/27727185/5c372eca-c12d-4dd5-8f24-5e9c6a45a14e">
Even after pip install I am getting no module found

**Comment by morrisonak** [comment]
I was having the same issue,  and was able to fix it with this:  
pip install altair==4

**Comment by jmayank23** [comment]
Thanks, that fixed it!
